name: training_app
description: App designed for personal trainers to allow tracking their clients progress.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # icons
  cupertino_icons: ^0.1.3
  material_design_icons_flutter: ^4.0.5555

  # data classes helpers
  equatable: ^2.0.0
  json_annotation: ^3.1.0

  # state management
  provider: ^4.3.2+2

  # storage
  path: ^1.7.0
  path_provider: ^1.6.18

  # other
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.5
  build_runner: ^1.10.1

flutter:

  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 900